eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8769

spring:
  application:
    name: zuul

zuul:
  routes:
    api-ribbon:
      path: /ribbon/**
      serviceId: ribbon
    api-fegin:
      path: /fegin/**
      serviceId: feign
