spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TheOddDyrus/repository/
          search-paths:
          username:
          password:
      label: master

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/